export const userConstants = {
  CREATE_USER: "CREATE_USER",
  GET_USERS: "GET_USERS",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  CLEAR_USER: "CLEAR_USER",
  UPDATE_DROITS_USER_BY_ID: "UPDATE_DROITS_USER_BY_ID",
  DELETE_USER: "DELETE_USER"
};
